spring:
  #线程池配置信息
  thread:
    pool:
      corePoolSize: 10
      maxPoolSize: 100
      keepAliveSeconds: 120
      queueCapacity: 200
      waitForTasksToCompleteOnShutdown: true
      awaitTerminationSeconds: 30
  #redis配置信息
  redis:
    host: 127.0.0.1
    port: 6379
    otherDatabase: 11
    maxIdle: 200
    maxTotal: 1024
    maxWait: 1000
#  boot:
#   admin:
#      url: http://127.0.0.1:9078
#      client: 
#        name: WD-ODB
#management.security.enabled: false    
#socket配置信息
netty: 
  ip: 127.0.0.1
  port: 9098
  bossGroupCount: 4
  wokerGroupCount: 8
  keepAlive: true
  backlog: 1024
  
logging:
  config: classpath:log4j2.xml

server:
  port: 9180

#GPS+OBD 混合信息 redis key值
gpsObdMessage-key: gpsObdMessage_

obdTravelItineraryList-key: obdTravelItineraryList_

obdFaultCodeList-key: obdFaultCodeList_

