spring:
  #redis配置信息
  redis:
    host: 127.0.0.1
    port: 6379
    database: 10
  #数据库连接配置信息
  datasource:
    url: jdbc:mysql://47.98.39.45:9097/wdxc?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: 'root'
    password: '123456'
#  boot:
#    admin:
#      url: http://127.0.0.1:9078
#      client:
#         name: WD-BIZ
#management.security.enabled: false

server:
  port: 80

ticserver:
  url: http://47.98.39.45:9095/api/push/carcmd
biz:
  scTime: 30000

staticPath:  D:\static\common\
updateMediaUrl: http://47.98.39.45:9888/api/updateMedia
deleteZnzpRedisKeyUrl: http://47.98.39.45:9888/api/deleteRedisKey
