spring:
  #线程池配置信息
  thread:
    pool:
      corePoolSize: 10
      maxPoolSize: 100
      keepAliveSeconds: 120
      queueCapacity: 200
      waitForTasksToCompleteOnShutdown: true
      awaitTerminationSeconds: 30
  #redis配置信息
  redis:
    host: 127.0.0.1
    port: 6379
    database: 10
    otherDatabase: 11
    maxIdle: 200
    maxTotal: 1024
    maxWait: 1000
  #数据库连接配置信息
  datasource:
    url: jdbc:oracle:thin:@//47.98.39.45:1521/orcl
    username: 'C##wdxc_admin'
    password: 'wdxc123456'
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    cachePrepStmts: true
#  boot:
#   admin:
#      url: http://127.0.0.1:9078
#      client: 
#        name: WD-ZNZP
#management.security.enabled: false 
#mybatis配置信息
mybatis:
  configLocation: classpath:mybatis/MapperConfig.xml
  
#socket配置信息
netty: 
  ip: 127.0.0.1
  port: 8899
  bossGroupCount: 4
  wokerGroupCount: 8
  keepAlive: true
  backlog: 1024
  
logging:
  config: classpath:log4j2.xml
  
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
    - tk.mybatis.mapper.common.special.InsertListMapper
  identity: MYSQL

server:
  port: 9888

# 智能站牌-活动营销-图片推送
staticUrl: http://47.98.39.45:9092/

