spring:
  #线程池配置信息
  thread:
    pool:
      corePoolSize: 10
      maxPoolSize: 100
      keepAliveSeconds: 120
      queueCapacity: 200
      waitForTasksToCompleteOnShutdown: true
      awaitTerminationSeconds: 30
#接口配置，接口可以有多个地址，多个地址中间使用';'
interface:
  #设备状态更新接口，点火、熄火、离线
  status: http://127.0.0.1;http://127.0.0.1;
  #设备事件更新接口，急加速、急转弯、急刹车、碰撞、超速
  event: http://127.0.0.1;
  #设备GPS上报处理接口
  gps: http://127.0.0.1;
  
logging:
  config: classpath:log4j2.xml
  
mapper:
  identity: MYSQL
  
