ALTER TABLE "C##WDXC_ADMIN"."CL_DD"
MODIFY ("JGDM" VARCHAR2(64 BYTE) )
MODIFY ("JGMC" VARCHAR2(128 BYTE) )

ALTER TABLE "C##WDXC_ADMIN"."CL_DDRZ"
MODIFY ("JGDM" VARCHAR2(64 BYTE) )
MODIFY ("JGMC" VARCHAR2(128 BYTE) )

ALTER TABLE "C##WDXC_ADMIN"."CL_DDLSB"
MODIFY ("JGDM" VARCHAR2(64 BYTE) )
MODIFY ("JGMC" VARCHAR2(128 BYTE) )

ALTER TABLE "C##WDXC_ADMIN"."CL_DZWL"
MODIFY ("JGDM" VARCHAR2(64 BYTE) )
MODIFY ("JGMC" VARCHAR2(128 BYTE) )