ALTER TABLE CL_DD ADD JJRSC NUMBER NULL;
COMMENT ON COLUMN CL_DD.JJRSC IS '节假日时长';
ALTER TABLE CL_DD ADD JBF NUMBER NULL;
COMMENT ON COLUMN CL_DD.JBF IS '加班费';
ALTER TABLE CL_DD ADD JBFDJ NUMBER NULL;
COMMENT ON COLUMN CL_DD.JBFDJ IS '加班费单价';

ALTER TABLE CL_DD ADD JJRDJ NUMBER NULL;
COMMENT ON COLUMN CL_DD.JJRDJ IS '节假日单位';
COMMENT ON COLUMN CL_DD.JJRDJ IS '节假日单价';

COMMENT ON COLUMN SYS_RLB.ZT IS '状态 1、正常上班，不等于1 是节假日';
COMMENT ON COLUMN SYS_HSGS.LX IS '类型 字典(ZDCLK0036) 10、里程  20 加班 30节假日';

ALTER TABLE CL_DD ADD JJRJL NUMBER NULL;
COMMENT ON COLUMN CL_DD.JJRJL IS '节假日金额';


DELETE FROM SYS_ZDXM WHERE ZDLMDM='ZDCLK0036'

INSERT INTO SYS_ZDXM (ZD_ID, ZDLMDM, ZDDM, ZDMC, QZ, CJSJ, CJR, BY1, BY2, BY3) VALUES ('ZDCLK00360001', 'ZDCLK0036', '00', '里程', null, TO_TIMESTAMP('2018-03-19 17:12:05', 'YYYY-MM-DD HH24:MI:SS'), '1-超级管理员', null, null, null);
INSERT INTO SYS_ZDXM (ZD_ID, ZDLMDM, ZDDM, ZDMC, QZ, CJSJ, CJR, BY1, BY2, BY3) VALUES ('ZDCLK00360002', 'ZDCLK0036', '10', '加班', null, TO_TIMESTAMP('2018-03-19 17:12:05', 'YYYY-MM-DD HH24:MI:SS'), '1-超级管理员', null, null, null);
INSERT INTO SYS_ZDXM (ZD_ID, ZDLMDM, ZDDM, ZDMC, QZ, CJSJ, CJR, BY1, BY2, BY3) VALUES ('ZDCLK00360003', 'ZDCLK0036', '20', '节假日', null, TO_TIMESTAMP('2018-03-19 17:12:05', 'YYYY-MM-DD HH24:MI:SS'), '1-超级管理员', null, null, null);



ALTER TABLE CL_XC MODIFY XC_START_END VARCHAR2(500) DEFAULT NULL;
COMMENT ON COLUMN CL_XC.XC_START_END IS '行程的开始和结束点 长度增加到500';



--生产环境还没有更新 ，需要联系肖老师，更新数据库

