module.exports = {
	SWIPER:{
		QUERTY:'/put/xl/getadsense'//轮播图片
	},
	LINE:{
		QUERTY:'/put/xl/getAll'//线路信息
	},
	LINEMESS:{
		QUERTY:'/put/xl/getzdcl'//车辆到站信息
	},
  LOGIN:{
    QUERTY:'/put/jsy/getjsy',//登录
  },
  MESLIST:{//订单列表
    QUERTY:'/put/dd/getsjlist'
  },
  LISTOK:{//行程确认
    CHANGE:'/put/dd/update'
  },
  GPS:{
	  DOT:'/put/dd/getStartPointAndEndPoint'
  }
}
