spring:
  #redis配置信息
  redis:
    host: 10.113.4.70
    port: 6379
    password: 'whCarRDB**'
  #数据库连接配置信息
  datasource:
    url: jdbc:oracle:thin:@//10.113.1.50:1521/orcl
    username: 'ucarmanage'
    password: 'tahQuoaj0Fi2'

server:
  port: 9099


wechat:
  cp:
    corpId: wxfcad74c01e52486e
    secret:  i7kMxAQJIASkXDFdGvYhUgFynhxEvtB2jOCFIrT6tYj3ZY41JNr7yUYDoKBFU6ez
    token: wdxc18
    aesKey: tjlq1glUbSsxADd2fsxExFvDUDo1RgdoQveqrSWyhoy
    agentId: 37
#静态文件根目录
staticPath: /app/data/nginx/staticpath
