
 COMMENT ON TABLE C##WDXC_ADMIN.SYS_PTJG IS '平台机构表';
 COMMENT ON TABLE C##WDXC_ADMIN.SYS_PTRZ IS '平台日志表';
 COMMENT ON TABLE C##WDXC_ADMIN.CL_CL IS '车辆表';
 COMMENT ON TABLE C##WDXC_ADMIN.CL_CLYXJL IS '车辆运行记录表';
 COMMENT ON TABLE C##WDXC_ADMIN.CL_CSSD IS '车辆超速表';
 COMMENT ON TABLE C##WDXC_ADMIN.CL_DD IS '订单主表';
 COMMENT ON TABLE C##WDXC_ADMIN.CL_DDLSB IS '订单历史表(原始单据表)';
 COMMENT ON TABLE C##WDXC_ADMIN.CL_DDRZ IS '订单日期表(订单流程日志表)';
 COMMENT ON TABLE C##WDXC_ADMIN.SYS_ZDXM IS '平台字典表';
 COMMENT ON TABLE C##WDXC_ADMIN.SYS_ZDLM IS '平台字典类目表(字典类别)';
 COMMENT ON TABLE C##WDXC_ADMIN.CL_DZWL IS '电子围栏表';
 COMMENT ON TABLE C##WDXC_ADMIN.CL_DZWL_CL IS '电子围栏车辆表';
 COMMENT ON TABLE C##WDXC_ADMIN.SYS_PTRZ IS '平台日志表';
 COMMENT ON TABLE C##WDXC_ADMIN.SYS_PTJG IS '平台机构表';
 COMMENT ON TABLE C##WDXC_ADMIN.SYS_PTJG IS '平台机构表';
 COMMENT ON TABLE C##WDXC_ADMIN.CL_DD IS '平台订单表';


 ALTER TABLE C##WDXC_ADMIN.CL_DD ADD SJ_SX CHAR(2) NULL;
 COMMENT ON COLUMN C##WDXC_ADMIN.CL_DD.SJ_SX IS '司机属性：10:内部司机，关联CL_JSY表 11：外部车，关联临时车表';

 ALTER TABLE C##WDXC_ADMIN.CL_DD ADD DZBH VARCHAR2(32) NULL;
 COMMENT ON COLUMN C##WDXC_ADMIN.CL_DD.DZBH IS '队长编号';
 ALTER TABLE C##WDXC_ADMIN.CL_DD ADD CDBH VARCHAR2(32) NULL;
 COMMENT ON COLUMN C##WDXC_ADMIN.CL_DD.CDBH IS '车队编号';




 COMMENT ON COLUMN C##WDXC_ADMIN.CL_DD.SJ_SX IS '属性：字典项(ZDCLK0039) 10:内部司机，关联CL_JSY表 11：外部车，关联临时车表';
--字典项编码
INSERT INTO C##WDXC_ADMIN.SYS_ZDLM (LMDM, LMMC, CJSJ, CJR, XGSJ, XGR, QZ)
VALUES ('ZDCLK0039', '司机属性：10:内部司机 11：外部车', TO_TIMESTAMP('2018-03-16 09:09:53', 'YYYY-MM-DD HH24:MI:SS'), '1', null, null, 38);
--字典项
 INSERT INTO C##WDXC_ADMIN.SYS_ZDXM (ZD_ID, ZDLMDM, ZDDM, ZDMC, QZ, CJSJ, CJR, BY1, BY2, BY3)
 VALUES ('ZDCLK00390001', 'ZDCLK0039', '10', '内部司机', null, TO_TIMESTAMP('2018-03-19 17:12:05', 'YYYY-MM-DD HH24:MI:SS'), '1-超级管理员', null, null, null);

 INSERT INTO C##WDXC_ADMIN.SYS_ZDXM (ZD_ID, ZDLMDM, ZDDM, ZDMC, QZ, CJSJ, CJR, BY1, BY2, BY3)
 VALUES ('ZDCLK00390002', 'ZDCLK0039', '11', '外部车', null, TO_TIMESTAMP('2018-03-19 17:12:05', 'YYYY-MM-DD HH24:MI:SS'), '1-超级管理员', null, null, null);


 COMMENT ON COLUMN C##WDXC_ADMIN.CL_DD.CLLX IS '车辆类型 字典项：ZDCLK0001：号牌种类 01、大型汽车 02、小型汽车 03、校园巴士';
--订单主表增加终端编号
ALTER TABLE C##WDXC_ADMIN.CL_DD ADD ZDBH VARCHAR2(32) NULL;
COMMENT ON COLUMN C##WDXC_ADMIN.CL_DD.ZDBH IS '终端编号';

--车辆表增加一个OBD编号
ALTER TABLE C##WDXC_ADMIN.CL_CL ADD OBD_CODE VARCHAR2(32) NULL;
COMMENT ON COLUMN C##WDXC_ADMIN.CL_CL.OBD_CODE IS 'OBD编号';



